mqtt:
  host: 127.0.0.1
  port: 1883

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-vaapi

lpr:
  enabled: true
  model_size: small
  min_area: 1000
  min_plate_length: 5
  recognition_threshold: 0.85

go2rtc:
  streams: {}

cameras: {}

record:
  enabled: true
  alerts:
    retain:
      days: 14
  detections:
    retain:
      days: 14
  motion:
    days: 14

version: 0.17-0

logger:
  default: info
  logs:
    frigate.data_processing.common.license_plate: debug
